app:
 myport: ${PORT:0}

spring:
 application:
  name: ApiJones-service
  
server:
 port: ${app.myport}

eureka:
 instance:
  instance-id: ${spring.application.name}:${random.value}
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/