spring:
 application:
  name: gateway
 cloud:
  gateway:
   routes:
    - id: pessoa
      uri: lb://pessoa-service
      filters:
       - StripPrefix=1
      predicates:
       - Path=/pessoa/**
    - id: peca
      uri: lb://peca-service
      filters:
       - StripPrefix=1
      predicates:
       - Path=/peca/**
    - id: fabrica
      uri: lb://fabrica-service
      filters:
       - StripPrefix=1
      predicates:
       - Path=/fabrica/**
    - id: encomendas
      uri: lb://encomendas-service
      filters:
       - StripPrefix=1
      predicates:
       - Path=/encomendas/**
    - id: Zipkin
      uri: http://localhost:9411/
      predicates:
       - Path=/** 
eureka:
 client:
  service-url:
   defaultUrl: http://localhost:8761/eureka
   
server:
 port: 9098

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
